### ISSUE TITLE
issue when istalling from a clean conda

### ISSUE THREAD

**Issue by AndGob** [ingmbioinfo/cia#13]
```
$ conda create --name CIA_pip python ipykernel
$ conda activate CIA_pip
$ pip install cia-python
```

Error:
Collecting cia-python
  Using cached cia_python-1.0a4-py3-none-any.whl.metadata (3.7 kB)
Collecting seaborn (from cia-python)
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting numpy (from cia-python)
  Downloading numpy-2.2.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting pandas (from cia-python)
  Downloading pandas-2.2.3-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting AnnData (from cia-python)
  Using cached anndata-0.11.1-py3-none-any.whl.metadata (8.2 kB)
Collecting scanpy (from cia-python)
  Using cached scanpy-1.10.4-py3-none-any.whl.metadata (9.3 kB)
Collecting array-api-compat!=1.5,>1.4 (from AnnData->cia-python)
  Using cached array_api_compat-1.9.1-py3-none-any.whl.metadata (1.6 kB)
Collecting h5py>=3.6 (from AnnData->cia-python)
  Downloading h5py-3.12.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting natsort (from AnnData->cia-python)
  Using cached natsort-8.4.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: packaging>=20.0 in /mnt/home/gobbini/miniconda3/envs/CIA_pip/lib/python3.13/site-packages (from AnnData->cia-python) (24.2)
Collecting scipy>1.8 (from AnnData->cia-python)
  Downloading scipy-1.14.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /mnt/home/gobbini/miniconda3/envs/CIA_pip/lib/python3.13/site-packages (from pandas->cia-python) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas->cia-python)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->cia-python)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting joblib (from scanpy->cia-python)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting legacy-api-wrap>=1.4 (from scanpy->cia-python)
  Using cached legacy_api_wrap-1.4.1-py3-none-any.whl.metadata (2.1 kB)
Collecting matplotlib>=3.6 (from scanpy->cia-python)
  Downloading matplotlib-3.10.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting networkx>=2.7 (from scanpy->cia-python)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting numba>=0.56 (from scanpy->cia-python)
  Downloading numba-0.60.0.tar.gz (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 45.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/mnt/home/gobbini/miniconda3/envs/CIA_pip/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/mnt/home/gobbini/miniconda3/envs/CIA_pip/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/home/gobbini/miniconda3/envs/CIA_pip/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-09nm03sf/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-09nm03sf/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-09nm03sf/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-09nm03sf/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 51, in <module>
        File "<string>", line 48, in _guard_py_ver
      RuntimeError: Cannot install on Python version 3.13.1; only versions >=3.9,<3.13 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by AndGob** [comment]
seems an issue with the python version. Downgrade python at v3.12 solve the issue:
```
> conda install python==3.12
```

**Required** check the compatibility with further python versions.
